[build]
  publish = "dist"
  command = "npm run build:netlify"

[[redirects]]
  from = "/api/*"
  to = "https://simconsultoria-backend.onrender.com/api/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
